# Uncomment the next line to define a global platform for your project
 # platform :ios, '14.1' 

target 'NHFK_HolidayDrive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NHFK_HolidayDrive

# Add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'

# Add the pods for any other Firebase products you want to use in your app
# For example, to use Firebase Authentication and Cloud Firestore
pod 'Firebase/Auth'
pod 'FirebaseUI'
pod 'FirebaseUI/Auth'
pod 'FirebaseUI/Facebook'
pod 'FBSDKLoginKit'
pod 'IQKeyboardManagerSwift'
pod 'Stripe'
    

pod 'Firebase/Firestore'

# Optionally, include the Swift extensions if you're using Swift.
pod 'FirebaseFirestoreSwift'

  target 'NHFK_HolidayDriveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NHFK_HolidayDriveUITests' do
    # Pods for testing
  end

end
