# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NHFK_HolidayDrive' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NHFK_HolidayDrive

  target 'NHFK_HolidayDriveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NHFK_HolidayDriveUITests' do
    # Pods for testing
  end

end
